import { useAppState } from '../state/app-state';

export const useProofs = () => {
  const {
    proofs,
    issuedEnvelopes,
    questClaims,
    scanHistory,
    ticketRedemptions,
    createProof,
    createQuestEnvelope,
    createTicketEnvelope,
    issueNotarizeEnvelope,
    encodeEnvelopeToQr,
    decodeEnvelopeFromQr,
    verifyEnvelope,
    claimQuest,
    checkTicketRedeemed,
    redeemTicket,
    addScanHistory,
    verifyProof,
    verifyMultipleProofs,
    deleteProofbookItem,
    loading,
    error,
    clearError,
  } = useAppState();

  return {
    proofs,
    issuedEnvelopes,
    questClaims,
    scanHistory,
    ticketRedemptions,
    createProof,
    createQuestEnvelope,
    createTicketEnvelope,
    issueNotarizeEnvelope,
    encodeEnvelopeToQr,
    decodeEnvelopeFromQr,
    verifyEnvelope,
    claimQuest,
    checkTicketRedeemed,
    redeemTicket,
    addScanHistory,
    verifyProof,
    verifyMultipleProofs,
    deleteProofbookItem,
    loading,
    error,
    clearError,
  };
};
