import { useAppState } from '../state/app-state';

export const useProofs = () => {
  const {
    proofs,
    issuedEnvelopes,
    questClaims,
    scanHistory,
    ticketRedemptions,
    createProof,
    createQuestEnvelope,
    createTicketEnvelope,
    createEventEnvelope,
    issueNotarizeEnvelope,
    encodeEnvelopeToQr,
    decodeEnvelopeFromQr,
    encodeEntryPassToQr,
    decodeEntryPassFromQr,
    verifyEnvelope,
    claimQuest,
    checkTicketRedeemed,
    redeemTicket,
    getEventClaimStats,
    claimEventPass,
    verifyEntryPassClaim,
    checkEntryPassRedeemed,
    redeemEntryPass,
    addScanHistory,
    verifyProof,
    verifyMultipleProofs,
    loading,
    error,
    clearError,
  } = useAppState();

  return {
    proofs,
    issuedEnvelopes,
    questClaims,
    scanHistory,
    ticketRedemptions,
    createProof,
    createQuestEnvelope,
    createTicketEnvelope,
    createEventEnvelope,
    issueNotarizeEnvelope,
    encodeEnvelopeToQr,
    decodeEnvelopeFromQr,
    encodeEntryPassToQr,
    decodeEntryPassFromQr,
    verifyEnvelope,
    claimQuest,
    checkTicketRedeemed,
    redeemTicket,
    getEventClaimStats,
    claimEventPass,
    verifyEntryPassClaim,
    checkEntryPassRedeemed,
    redeemEntryPass,
    addScanHistory,
    verifyProof,
    verifyMultipleProofs,
    loading,
    error,
    clearError,
  };
};
